[package]
name = "neatcore"
version = "0.1.0"
edition = "2021"

[dependencies]
network = { path = "../network" }
innovation = { path = "../innovation" }
timer = { path = "../timer" }

rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"